group: travis_latest
language: node_js
node_js: "11"
env:
  - REPO=BrainJS/brain.js
  - REPO=i0natan/nodebestpractices
  - REPO=vuejs/vue
  - REPO=iamkun/dayjs
  - REPO=swc-project/swc
  - REPO=trekhleb/javascript-algorithms
  - REPO=facebook/react
  - REPO=SaraVieira/fiddly

install: npm install -g eslint eslint-plugin-import eslint-plugin-node eslint-plugin-promise flatted --save-dev
before_script:
  - URL=https://github.com/${REPO}
  - git clone --depth=50 ${URL} ${REPO}  # --branch=master
script:
  - echo ; echo -n "eslint testing of ${URL} on " ; node --version
  - eslint --config eslintrc.json ${REPO}
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
